{% set name = "pst-classifier" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Schlieplab/PstClassifierSeqan/releases/download/v.1.0/PstClassifierSeqan.tar.gz
  sha256: ec7e29c92fb131e271f6a995e6bd815c5924ecb3043e1c15d46672f48975a1bc

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.7
    - make
  host:
    - highfive
    - zlib
    - eigen
    - bzip2
  run:
    - bzip2
    - zlib
    - eigen
    - highfive

test:
  commands:
    - pst-classifier --help
    - probabilistic_suffix_tree_map_tests

about:
  home: https://github.com/Schlieplab/PstClassifierSeqan
  dev_url: https://github.com/Schlieplab/PstClassifierSeqan
  license: BSD-3-Clause
  license_family: BSD
    #license_file: LICENSE.md
  summary: 'Variable-length Markov chain construction using a lazy suffix tree.'

extra:
  maintainers:
    - kalior
