package:
  name: 'cmip'
  version: '2.6.7'

source:
  url: http://mmb.irbbarcelona.org/gitlab/gelpi/CMIP/raw/f3fccbfd01aa64b1a0faf68e929da57ac9f7691e/cmip.tar.gz
  sha256: a437903e59cdd230d45bf292b4598a79d551fb504b14c9569191bad638b0db24

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make

test:
  commands:
    - cmip -h

about:
  home: http://mmb.irbbarcelona.org/gitlab/gelpi/CMIP
  license: Apache Software License
  license_family: APACHE
  summary: CMIP Classical Molecular Interaction Potentials
  description: "The latest version of the classical molecular interaction potential (CMIP) has the ability to predict the position of crystallographic waters in several proteins with great accuracy."
